### ISSUE TITLE
git clone 文件太大

### ISSUE THREAD

**Issue by tjadamlee** [athena-team/athena#307]
git clone时候，需要下载的文件太大了，是否排查下大文件？

**Comment by tjadamlee** [comment]
@tjadamlee @Some-random

**Comment by Some-random** [comment]
The problem is git pack file contains lots of outdated refs as illustrated in [this article](https://stackoverflow.com/questions/11050265/remove-large-pack-file-created-by-git) I used this [tool](https://github.com/newren/git-filter-repo) and shrank the size of .git folder from 400Mb to 7.2Mb. 

One problem this approach might bring is it changed all hash values of previous commits and closes all outstanding pull requests. So users are encouraged to make a fresh clone of this repo and we will make sure this cleanup wouldn't cause other problems.

**Comment by tjadamlee** [comment]
done
